FROM archlinux:latest

RUN pacman -Syu --noconfirm sudo \
    && pacman -Scc --noconfirm

RUN useradd -m -s /bin/bash user && echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers

COPY . /home/user/.dotfiles
RUN chown -R user:user /home/user/.dotfiles

USER user
WORKDIR /home/user/.dotfiles
