FROM archlinux:latest

RUN pacman -Syu --noconfirm sudo git \
    && pacman -Scc --noconfirm

RUN useradd -m -s /bin/bash user && echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers
USER user

RUN git clone https://github.com/antoniosubasic/dotfiles.git /home/user/.dotfiles

WORKDIR /home/user/.dotfiles
