#!/bin/sh

if [ "$(id -u)" -eq 0 ]; then
    printf "must not be run as root\n" >&2
    exit 1
fi

if ! sudo -v; then
    printf "sudo is required\n" >&2
    exit 1
fi

if [ ! -d "$HOME/.config" ]; then
    mkdir -p "$HOME/.config"
fi

CWD="$(dirname "$(realpath "$0")")"
BASE="$CWD"/scripts/base

. "$BASE"

case "$OS" in
    ubuntu|linuxmint|arch|endeavouros) ;;
    *)
        printf "unsupported OS: %s\n" "$OS" >&2
        exit 1
        ;;
esac

scripts_pattern="^$CWD/scripts/[0-9][0-9]$([ "$IS_WSL" -ne 0 ] && printf "!?")_.*\.sh$"
scripts="$(find "$CWD/scripts" -type f -regex "$scripts_pattern" | sort)"
total="$(echo "$scripts" | wc -l)"
count=0
for script in $scripts; do
    printf "=== %s ===\n" "$(printf "$script" | sed -E "s|$CWD/scripts/[0-9]{2}!?_||; s|\.sh$||; s|_| |")"

    sh "$script" "$BASE"
    [ $? -ne 0 ] && exit $?

    count=$((count + 1))
    if [ "$count" -lt "$total" ]; then
        printf "\n"
    fi
done