[general]
import = [
    "~/.config/alacritty/themes/tokyo_night.toml"
]

[window]
dimensions = { columns = 125, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "full"
opacity = 0.99

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "BoldItalic" }

[keyboard]
bindings = [
    { key= "N", mods= "Control", action= "SpawnNewInstance" }
]
